import { Link } from 'react-router-dom';
import { CopyMarkdownButton } from '../components/CopyMarkdownButton';
import developersMd from './docs-developers.md?raw';

/**
 * Developer-side docs. Walks a consumer through getting set up
 * (MetaMask, Sepolia ETH, faucets), registering for their first
 * service, running attestations, calling APIs from code, and managing
 * their key over time.
 *
 * The "from code" section is the load-bearing one — most readers will
 * jump straight to the JS/TS auth flow once they have an attestation.
 */
export function DocsDevelopers() {
  return (
    <section className="page docs">
      <div className="docs__top-actions">
        <Link to="/docs" className="back-link mono">
          ← all docs
        </Link>
        <CopyMarkdownButton markdown={developersMd} />
      </div>

      <header className="page__head">
        <div className="page__eyebrow mono">// developer docs · consumer guide</div>
        <h1 className="page__title">Use APIs from the NullFetch marketplace</h1>
        <p className="page__desc">
          Set up a wallet, register for a service, and call its API from
          your code. Your API keys are generated by your browser, never
          stored at the provider or the marketplace. Possession is
          proven on-chain; the rest is a normal HTTP call.
        </p>
      </header>

      {/* ── table of contents ──────────────────────────────────── */}
      <nav className="docs__toc mono" aria-label="On this page">
        <div className="docs__toc-label">// on this page</div>
        <ul>
          <li><a href="#overview">01 · overview</a></li>
          <li><a href="#prerequisites">02 · prerequisites</a></li>
          <li><a href="#first-register">03 · register for your first service</a></li>
          <li><a href="#attest">04 · run an attestation</a></li>
          <li><a href="#call">05 · call the api from code</a></li>
          <li><a href="#server">06 · calling from a server / ci</a></li>
          <li><a href="#refresh">07 · attestation lifetime + refresh</a></li>
          <li><a href="#rotate">08 · key rotation + storage</a></li>
          <li><a href="#revoked">09 · revocation + recovery</a></li>
          <li><a href="#errors">10 · error codes you might see</a></li>
          <li><a href="#cost">11 · cost model</a></li>
          <li><a href="#references">12 · reference clients</a></li>
          <li><a href="#faq">13 · faq</a></li>
          <li><a href="#help">14 · need help</a></li>
        </ul>
      </nav>

      {/* ── 01 overview ────────────────────────────────────────── */}
      <section id="overview" className="docs__section">
        <h2 className="docs__h2 mono">01 · overview</h2>
        <p>
          As a developer using NullFetch, you do four things over the
          lifetime of a subscription:
        </p>
        <ol className="docs__list">
          <li>
            <b>Register</b> for a service once. Your browser generates a
            random 32-byte API key, encrypts it client-side, and submits
            only the ciphertext on-chain. The plaintext is saved
            locally — by you, in your browser&rsquo;s storage.
          </li>
          <li>
            <b>Attest</b> when you want to use the API. Re-encrypt your
            key, prove on-chain that it matches the ciphertext on file,
            and publish the result. Valid for 1 hour by default.
          </li>
          <li>
            <b>Call the API</b> using a SIWE-style wallet signature per
            request. The provider&rsquo;s server reads your attestation
            and gates the response. No gas per call.
          </li>
          <li>
            <b>Refresh</b> the attestation when it expires (or rotate
            your key if you want a new one).
          </li>
        </ol>
        <p>
          The marketplace contract and the provider both see only
          ciphertext. Your plaintext key exists only on the device that
          generated it.
        </p>
      </section>

      {/* ── 02 prerequisites ───────────────────────────────────── */}
      <section id="prerequisites" className="docs__section">
        <h2 className="docs__h2 mono">02 · prerequisites</h2>
        <div className="docs__table-wrap">
          <table className="docs__table mono">
            <thead>
              <tr><th>Need</th><th>For</th><th>How to get it</th></tr>
            </thead>
            <tbody>
              <tr>
                <td>MetaMask</td>
                <td>Wallet + signing</td>
                <td>
                  <a href="https://metamask.io" target="_blank" rel="noopener noreferrer">
                    metamask.io
                  </a>{' '}
                  — browser extension, free
                </td>
              </tr>
              <tr>
                <td>Sepolia network in MetaMask</td>
                <td>Talking to the marketplace</td>
                <td>The app prompts you to switch + add Sepolia on connect</td>
              </tr>
              <tr>
                <td>~0.01 Sepolia ETH</td>
                <td>Registration fee + a few attestations</td>
                <td>
                  Faucets:{' '}
                  <a href="https://sepoliafaucet.com" target="_blank" rel="noopener noreferrer">
                    sepoliafaucet.com
                  </a>,{' '}
                  <a href="https://www.alchemy.com/faucets/ethereum-sepolia" target="_blank" rel="noopener noreferrer">
                    Alchemy
                  </a>,{' '}
                  <a href="https://faucets.chain.link/sepolia" target="_blank" rel="noopener noreferrer">
                    Chainlink
                  </a>
                </td>
              </tr>
              <tr>
                <td>A modern browser</td>
                <td>The marketplace UI</td>
                <td>Chrome, Firefox, Edge, Brave — anything with WebAssembly + ES2022</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="docs__note mono">
          // Sepolia ETH is fake money. You don&rsquo;t pay real
          anything until / unless this moves to mainnet.
        </p>
      </section>

      {/* ── 03 first register ──────────────────────────────────── */}
      <section id="first-register" className="docs__section">
        <h2 className="docs__h2 mono">03 · register for your first service</h2>

        <h3 className="docs__h3">1. Find a service</h3>
        <p>
          Open <Link to="/browse">/browse</Link>. Every listed service
          is visible without a wallet. Click any card to see its
          provider, endpoint, category, and current subscriber count.
        </p>

        <h3 className="docs__h3">2. Click &ldquo;Register for this service&rdquo;</h3>
        <p>
          You&rsquo;ll land on <code>/developer/register/N</code>. The
          page shows the registration fee (0.0003 Sepolia ETH) and the
          service&rsquo;s current status.
        </p>

        <h3 className="docs__h3">3. Watch what happens before MetaMask prompts</h3>
        <p>Your browser:</p>
        <ul className="docs__list">
          <li>Generates 32 random bytes with <code>crypto.getRandomValues</code></li>
          <li>Computes <code>keccak256</code>, splits the hash into hi/lo halves</li>
          <li>
            Encrypts both halves locally using Zama&rsquo;s WASM SDK and
            produces a zero-knowledge proof of plaintext knowledge
          </li>
        </ul>
        <p>
          Only the ciphertext + proof go to MetaMask. The plaintext key
          never leaves your machine.
        </p>

        <h3 className="docs__h3">4. Confirm in MetaMask + pay the fee</h3>
        <p>
          You&rsquo;ll see a transaction for 0.0003 ETH. Confirm. Wait
          ~15 seconds for the tx to mine.
        </p>

        <h3 className="docs__h3">5. Save your key — one-time reveal</h3>
        <p>
          The success page shows your plaintext API key behind a
          &ldquo;Reveal&rdquo; button. Click it, copy the key
          somewhere you trust (password manager, secure notes), and
          check the acknowledgement box.
        </p>
        <p>
          The key is also auto-saved to this browser&rsquo;s local
          storage, encrypted with a wallet-signature-derived key (see
          the threat-model doc for details). But you should keep a
          backup outside the browser too.
        </p>
        <p className="docs__note mono">
          // If you lose the plaintext key, the provider must revoke
          your subscription and you must register again (paying the
          fee again). There&rsquo;s no recovery.
        </p>
      </section>

      {/* ── 04 attest ──────────────────────────────────────────── */}
      <section id="attest" className="docs__section">
        <h2 className="docs__h2 mono">04 · run an attestation</h2>
        <p>
          Before you can call a NullFetch-gated API, you need a
          <b> fresh attestation</b> on-chain. This is what proves to the
          provider that you currently hold the right key, without ever
          showing them the key.
        </p>

        <h3 className="docs__h3">1. Open the use page</h3>
        <p>
          Go to <code>/developer/service/N</code> for the service you
          registered for. Your key auto-fills from local storage (you
          may be prompted to unlock with a wallet signature).
        </p>

        <h3 className="docs__h3">2. Click &ldquo;run on-chain attestation&rdquo;</h3>
        <p>
          This is a two-transaction flow on Sepolia:
        </p>
        <ol className="docs__list">
          <li>
            <b><code>verifyAndAttest</code></b> — re-encrypts your key,
            compares it to the on-chain ciphertext under FHE, and marks
            the result publicly decryptable. Costs ~300K gas.
          </li>
          <li>
            <b><code>submitAttestation</code></b> — Zama&rsquo;s KMS
            decrypts the comparison result and writes the cleartext
            boolean to the contract. Costs ~250K gas.
          </li>
        </ol>
        <p>
          Both txs require a MetaMask confirmation. Total elapsed time:
          ~30 seconds. After both mine, you have a fresh attestation
          valid for 1 hour.
        </p>
        <p>
          The attestation is keyed by your wallet, not by the API
          itself. One attestation per (wallet, service); refreshing
          overwrites the previous one.
        </p>
      </section>

      {/* ── 05 call from code ──────────────────────────────────── */}
      <section id="call" className="docs__section">
        <h2 className="docs__h2 mono">05 · call the api from code</h2>
        <p>
          Once you have a fresh attestation, each API call is a
          three-step dance: fetch a challenge, sign it, send the
          headers. No gas, no contract interaction.
        </p>
        <pre className="docs__code mono">{`import { BrowserProvider, getAddress } from 'ethers';

// the provider's deployed API base
const API = 'https://provider.example.dev';
const SERVICE_ID = 3;

async function call() {
  const provider = new BrowserProvider(window.ethereum);
  const signer = await provider.getSigner();

  // EIP-55 checksum — MetaMask returns lowercase, server rejects it
  const wallet = getAddress(await signer.getAddress());

  // 1. fetch a single-use challenge
  const cr = await fetch(\`\${API}/challenge?wallet=\${wallet}\`, {
    method: 'POST',
  });
  const { nonce, message } = await cr.json();

  // 2. sign the message with personal_sign (no tx, no gas)
  const signature = await signer.signMessage(message);

  // 3. call the gated endpoint
  const r = await fetch(\`\${API}/api/service/\${SERVICE_ID}\`, {
    headers: {
      'X-Wallet-Address': wallet,
      'X-Auth-Nonce': nonce,
      'X-Wallet-Signature': signature,
    },
  });

  return r.json();
}`}</pre>
        <p>
          The challenge is single-use and expires after 2 minutes. You
          fetch a fresh one for every call. The signature happens
          locally in MetaMask in well under a second — no popup
          required for <code>personal_sign</code> if MetaMask is
          configured to auto-approve same-origin signatures (most users
          do).
        </p>
        <p className="docs__note mono">
          // The exact endpoint path (<code>/api/service/:id</code>) is
          a convention the NullFetch reference uses, but providers can
          mount their gated endpoint anywhere. Check the provider&rsquo;s
          docs for the actual path.
        </p>
      </section>

      {/* ── 06 from server ─────────────────────────────────────── */}
      <section id="server" className="docs__section">
        <h2 className="docs__h2 mono">06 · calling from a server / ci</h2>
        <p>
          For server-side or CI use, swap <code>BrowserProvider</code>{' '}
          for an <code>ethers.Wallet</code> with a private key:
        </p>
        <pre className="docs__code mono">{`import { Wallet } from 'ethers';

const wallet = new Wallet(process.env.SEPOLIA_PRIVATE_KEY);
// wallet.address is already EIP-55 checksummed

const cr = await fetch(\`\${API}/challenge?wallet=\${wallet.address}\`, {
  method: 'POST',
});
const { nonce, message } = await cr.json();

const signature = await wallet.signMessage(message);

const r = await fetch(\`\${API}/api/service/\${SERVICE_ID}\`, {
  headers: {
    'X-Wallet-Address': wallet.address,
    'X-Auth-Nonce': nonce,
    'X-Wallet-Signature': signature,
  },
});`}</pre>
        <p>
          The wallet that signs here must be the same one that
          registered for the service and ran the attestation. If
          you&rsquo;re moving from browser usage to server usage,
          you&rsquo;ll need to export the private key of the wallet you
          used in the browser — or register again with a fresh wallet
          dedicated to the server.
        </p>
        <p className="docs__note mono">
          // Treat <code>SEPOLIA_PRIVATE_KEY</code> like any other
          secret. The wallet that registered for the service IS the
          credential for that subscription; leaking it leaks the
          subscription.
        </p>
      </section>

      {/* ── 07 attestation refresh ─────────────────────────────── */}
      <section id="refresh" className="docs__section">
        <h2 className="docs__h2 mono">07 · attestation lifetime + refresh</h2>
        <p>
          Default TTL: <b>1 hour</b>. Owner-settable on the marketplace
          contract, bounded to [1 min, 24 h].
        </p>
        <p>
          Within the TTL window, you can call the API as many times as
          you want — only the wallet signature per call, no gas. After
          expiration, the next call returns:
        </p>
        <pre className="docs__code mono">{`HTTP 401
{
  "error": "no_fresh_attestation",
  "detail": "No on-chain attestation within the 3600-second window.
             Run verifyAndAttest first.",
  "wallet": "0x..."
}`}</pre>
        <p>
          To refresh: go back to <code>/developer/service/N</code> and
          click &ldquo;run on-chain attestation&rdquo; again. Same
          two-tx flow as your first time. ~30 seconds elapsed, ~600K
          gas total.
        </p>
        <p>
          For high-frequency usage you can ask the provider (or the
          marketplace owner) to bump the TTL closer to the 24-hour
          maximum to amortize the refresh cost.
        </p>
      </section>

      {/* ── 08 rotation ────────────────────────────────────────── */}
      <section id="rotate" className="docs__section">
        <h2 className="docs__h2 mono">08 · key rotation + storage</h2>
        <p>
          Rotation generates a new random key and replaces the
          ciphertext stored against your subscription. Use it if you
          suspect your key was leaked, or as routine hygiene.
        </p>
        <p>
          <Link to="/developer">Developer dashboard</Link> → pick a
          subscription → &ldquo;rotate to a new random key.&rdquo;
          Costs gas only, no fee. The old key stops working
          immediately; the new key auto-fills + auto-saves locally.
        </p>
        <p>
          Rotation <b>does not affect your wallet identity</b> — your
          subscription history, your call count, and your provider-side
          logs all survive cleanly. The provider sees the same wallet
          calling them; the comparison just uses different ciphertext.
        </p>

        <h3 className="docs__h3">Where your plaintext key lives</h3>
        <ul className="docs__list">
          <li>
            <b>This browser&rsquo;s localStorage</b> — encrypted with a
            session key derived from a wallet signature. A passive disk
            dump or browser extension reading localStorage gets
            ciphertext only.
          </li>
          <li>
            <b>Wherever you backed it up</b> — password manager, secure
            notes, an encrypted file. You.
          </li>
        </ul>
        <p>
          The plaintext does NOT live: at the provider, at the
          marketplace, on the chain, in the relayer, or in Zama&rsquo;s
          KMS. Just the encrypting browser + your backup.
        </p>
      </section>

      {/* ── 09 revocation ──────────────────────────────────────── */}
      <section id="revoked" className="docs__section">
        <h2 className="docs__h2 mono">09 · revocation + recovery</h2>
        <p>
          A provider can revoke any subscription at any time. The next
          attestation attempt against a revoked subscription reverts
          on-chain. Your existing attestation (if still fresh) keeps
          working until the TTL expires — but you won&rsquo;t be able
          to refresh.
        </p>
        <p>To get re-access:</p>
        <ul className="docs__list">
          <li>
            Ask the provider to un-revoke (they have a per-subscription
            button on their dashboard). Sub-zero gas cost for them.
          </li>
          <li>
            Or: register again from scratch with a fresh wallet, paying
            the registration fee again. The provider can&rsquo;t prevent
            this (anyone can register), but they can revoke you again.
          </li>
        </ul>
        <p>
          Note: there&rsquo;s no &ldquo;developer-initiated
          unsubscribe&rdquo; today. If you want to stop using a service,
          just stop calling it. The fee is non-refundable.
        </p>
      </section>

      {/* ── 10 errors ──────────────────────────────────────────── */}
      <section id="errors" className="docs__section">
        <h2 className="docs__h2 mono">10 · error codes you might see</h2>
        <div className="docs__table-wrap">
          <table className="docs__table mono">
            <thead>
              <tr><th>Status</th><th>Error</th><th>What it means / what to do</th></tr>
            </thead>
            <tbody>
              <tr>
                <td>400</td>
                <td>missing_headers</td>
                <td>Forgot one of the three auth headers. Send all three.</td>
              </tr>
              <tr>
                <td>400</td>
                <td>bad_address</td>
                <td>
                  Wallet header isn&rsquo;t a valid Ethereum address.
                  Run it through <code>ethers.getAddress()</code> first.
                </td>
              </tr>
              <tr>
                <td>401</td>
                <td>no_challenge</td>
                <td>Skipped <code>POST /challenge</code>. Fetch one first.</td>
              </tr>
              <tr>
                <td>401</td>
                <td>nonce_mismatch</td>
                <td>You sent the wrong nonce. Re-fetch a challenge.</td>
              </tr>
              <tr>
                <td>401</td>
                <td>challenge_expired</td>
                <td>2-minute TTL elapsed. Re-fetch.</td>
              </tr>
              <tr>
                <td>401</td>
                <td>signature_mismatch</td>
                <td>
                  You signed with a different wallet than the one in the
                  header — or the header isn&rsquo;t EIP-55 checksummed.
                </td>
              </tr>
              <tr>
                <td>401</td>
                <td>no_fresh_attestation</td>
                <td>
                  Your attestation expired or doesn&rsquo;t exist. Run a
                  new <code>verifyAndAttest</code> at{' '}
                  <code>/developer/service/N</code>.
                </td>
              </tr>
              <tr>
                <td>401</td>
                <td>attestation_invalid</td>
                <td>
                  You attested but with the wrong key. Either you typed
                  the key wrong or your provider&rsquo;s stored
                  ciphertext is for a different subscription.
                </td>
              </tr>
              <tr>
                <td>401</td>
                <td>service_mismatch</td>
                <td>
                  Your latest attestation is for a different service. Go
                  back to <code>/developer/service/N</code> for{' '}
                  <i>this</i> service and attest there.
                </td>
              </tr>
              <tr>
                <td>502</td>
                <td>gate_not_ready</td>
                <td>
                  Provider&rsquo;s server hasn&rsquo;t completed
                  bootstrap (usually transient). Retry in 10-30 seconds.
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ── 11 cost ────────────────────────────────────────────── */}
      <section id="cost" className="docs__section">
        <h2 className="docs__h2 mono">11 · cost model</h2>
        <div className="docs__table-wrap">
          <table className="docs__table mono">
            <thead>
              <tr><th>Action</th><th>Cost</th><th>Frequency</th></tr>
            </thead>
            <tbody>
              <tr>
                <td>Register for a service</td>
                <td>0.0003 ETH + ~200K gas</td>
                <td>Once per service you join</td>
              </tr>
              <tr>
                <td>Run an attestation</td>
                <td>~600K gas total (2 txs)</td>
                <td>Once per TTL window (default 1h)</td>
              </tr>
              <tr>
                <td>Call the API</td>
                <td><b>No gas, no fee</b></td>
                <td>Unlimited within the TTL</td>
              </tr>
              <tr>
                <td>Rotate your key</td>
                <td>~200K gas (no fee)</td>
                <td>When you decide</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>
          On Sepolia, gas is play money. If/when this moves to mainnet,
          attestation refresh becomes the main recurring cost — bump
          the TTL to 24h to amortize.
        </p>
      </section>

      {/* ── 12 reference clients ───────────────────────────────── */}
      <section id="references" className="docs__section">
        <h2 className="docs__h2 mono">12 · reference clients</h2>
        <p>
          Working examples you can clone and adapt:
        </p>
        <ul className="docs__list">
          <li>
            <a href="https://github.com/ronniethedevv/quote-fetcher" target="_blank" rel="noopener noreferrer">
              quote-fetcher
            </a>{' '}
            — both a Node.js CLI (server-style auth with a private key)
            and a browser frontend (MetaMask-style auth). Both call the
            quote-api provider.
          </li>
          <li>
            <a href="https://github.com/ronniethedevv/quote-api" target="_blank" rel="noopener noreferrer">
              quote-api
            </a>{' '}
            — the provider these clients call. Useful for seeing what
            the gated server looks like from the other side.
          </li>
        </ul>
      </section>

      {/* ── 13 faq ─────────────────────────────────────────────── */}
      <section id="faq" className="docs__section">
        <h2 className="docs__h2 mono">13 · faq</h2>

        <h3 className="docs__h3">Do I need real ETH?</h3>
        <p>
          No. Sepolia is a testnet. Faucets give you free Sepolia ETH
          for development.
        </p>

        <h3 className="docs__h3">Where is my plaintext key actually stored?</h3>
        <p>
          Only in this browser&rsquo;s localStorage (encrypted with a
          session key derived from a wallet signature) and wherever you
          backed it up. Nothing else has a copy.
        </p>

        <h3 className="docs__h3">Can I use the same wallet for multiple services?</h3>
        <p>
          Yes. Each (wallet, service) pair has its own subscription
          with its own key. One wallet can hold many subscriptions.
        </p>

        <h3 className="docs__h3">Can I share a subscription across multiple machines?</h3>
        <p>
          Yes, if you copy the plaintext key to each machine and use
          the same wallet for signing. The local key store on the new
          machine will be empty — paste the key in manually on the use
          page, then save it locally.
        </p>

        <h3 className="docs__h3">What if I lose access to my wallet?</h3>
        <p>
          You lose the subscription. The wallet IS the identity; no
          wallet, no possession proof. Treat the wallet like any other
          credential.
        </p>

        <h3 className="docs__h3">What if I lose the plaintext key but still have the wallet?</h3>
        <p>
          Ask the provider to revoke your subscription and register
          again with the same wallet. You&rsquo;ll generate a new key
          and pay the registration fee again. (Or: rotate, if the old
          key isn&rsquo;t fully lost and the rotate flow still works
          with your current attestation.)
        </p>

        <h3 className="docs__h3">Does the provider see my requests?</h3>
        <p>
          They see your wallet address, the time of the request, and
          your call patterns — same as any API provider sees its
          customers. They don&rsquo;t see your key (ever). They can
          build their own usage analytics keyed by wallet.
        </p>

        <h3 className="docs__h3">Can I see how providers track my usage?</h3>
        <p>
          On-chain, yes:{' '}
          <code>getSubscription(serviceId, yourWallet)</code> returns a{' '}
          <code>callCount</code> if the provider opted into the
          contract&rsquo;s public counter. Off-chain, providers can
          track whatever they want; that&rsquo;s up to them.
        </p>
      </section>

      {/* ── 14 help ────────────────────────────────────────────── */}
      <section id="help" className="docs__section">
        <h2 className="docs__h2 mono">14 · need help</h2>
        <ul className="docs__list">
          <li>
            <b>Source &amp; issues:</b>{' '}
            <a href="https://github.com/ronniethedevv/nullfetch" target="_blank" rel="noopener noreferrer">
              github.com/ronniethedevv/nullfetch
            </a>
          </li>
          <li>
            <b>Marketplace contract on Sepolia:</b>{' '}
            <a
              href="https://sepolia.etherscan.io/address/0x77CD4B9b78946A20407fa1C1C8B3298401D93875#code"
              target="_blank" rel="noopener noreferrer"
            >
              0x77CD…3875 ↗
            </a>
          </li>
          <li>
            <b>Reference clients:</b>{' '}
            <a href="https://github.com/ronniethedevv/quote-fetcher" target="_blank" rel="noopener noreferrer">
              quote-fetcher
            </a>{' '}
            (CLI + frontend),{' '}
            <a href="https://github.com/ronniethedevv/quote-api" target="_blank" rel="noopener noreferrer">
              quote-api
            </a>{' '}
            (the provider they call)
          </li>
          <li>
            <b>Maintainer:</b>{' '}
            <a href="https://x.com/ronnie_thedev" target="_blank" rel="noopener noreferrer">
              @ronnie_thedev
            </a>
          </li>
        </ul>
      </section>
    </section>
  );
}
