import { Link } from 'react-router-dom';

/**
 * Docs landing page. Splits readers into providers and developers
 * before they get into specific guidance — the two audiences have very
 * different on-ramps and forcing one stream loses the other.
 */
export function DocsLanding() {
  return (
    <section className="page docs">
      <header className="page__head">
        <div className="page__eyebrow mono">// docs</div>
        <h1 className="page__title">Two paths through NullFetch</h1>
        <p className="page__desc">
          NullFetch is a confidential API marketplace built on Zama
          fhEVM. Providers list APIs without ever holding their
          subscribers&rsquo; keys; developers use those APIs with keys
          that exist only on their own machine. Pick your role to get
          the right setup.
        </p>
      </header>

      <div className="docs__paths">
        <Link to="/docs/providers" className="docs__path">
          <div className="docs__path-eyebrow mono">// for service providers</div>
          <div className="docs__path-title">You have an API</div>
          <p className="docs__path-desc">
            You want to list your API on NullFetch and gate it on
            on-chain attestations. No customer key database to leak. No
            custom signing logic to write.
          </p>
          <ul className="docs__path-list mono">
            <li>· Add the auth gate in 8 lines</li>
            <li>· Manage subscribers + revocations</li>
            <li>· Production checklist + error codes</li>
            <li>· Local dev with no real attestations</li>
          </ul>
          <div className="docs__path-cta mono">read the provider guide →</div>
        </Link>

        <Link to="/docs/developers" className="docs__path">
          <div className="docs__path-eyebrow mono">// for developers</div>
          <div className="docs__path-title">You want to use APIs</div>
          <p className="docs__path-desc">
            You want to call APIs from the NullFetch marketplace. Your
            keys are generated by your browser, encrypted under FHE on
            registration, and stored on disk only by you.
          </p>
          <ul className="docs__path-list mono">
            <li>· Set up MetaMask + get Sepolia ETH</li>
            <li>· Register for your first service</li>
            <li>· Call gated APIs from code</li>
            <li>· Manage attestations + key rotation</li>
          </ul>
          <div className="docs__path-cta mono">read the developer guide →</div>
        </Link>
      </div>

      <section className="docs__section">
        <h2 className="docs__h2 mono">// architecture in one paragraph</h2>
        <p>
          The marketplace contract on Sepolia holds the catalog and
          per-(service, wallet) ciphertext of every developer&rsquo;s
          API key. Providers run their own servers that read{' '}
          <code>getAttestation(wallet)</code> from the contract to gate
          responses. Developers prove possession of their key on-chain
          via{' '}
          <code>verify</code> / <code>verifyAndAttest</code> — the
          contract compares ciphertext to ciphertext using{' '}
          <code>FHE.eq</code>, never decrypting. Auth is a single
          boolean read; the actual API payload flows directly between
          developer and provider, never touching NullFetch.
        </p>
      </section>
    </section>
  );
}
